#!/usr/bin/env Rscript

######  
suppressMessages(library("docopt"))
"
Usage: 
	beta_diversity_permutations_one_twin_UPDATED_120115ERD.R -h | --help
	beta_diversity_permutations_one_twin_UPDATED_120115ERD.R --abo_file=<abo_file> --cov_file=<cov_file> --bc_file=<bc_file> --uu_file=<uu_file> --wu_file=<wu_file> --n=<n> --nproc=<nproc> --outpath=<outpath>

Description: This script will calculate a permutation p-value for beta-diversity differences within and between groups for ABO and SS (one twin only). 

Options:
	-h  --help			print arguments to screen
	--abo_file=<abo_file> 		file of phenotype data
	--cov_file=<cov_file> 		file of covariate information
	--bc_file=<bc_file>			file of bray curtis dissimilarity
	--uu_file=<uu_file>			file of unweighted unifrac distances
	--wu_file=<wu_file>			file of weighted unifrac distances
	--n=<n>						number of permutations to run (each perm takes 1.3s)
	--nproc=<nproc>				number of processors to use in parallel (4 on computer)
	--outpath=<outpath> 		directory to write results to
" -> doc
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()											# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
#############################



##### Load arguments:
opts <- docopt(doc)
#print(opts)
abo.file <- opts$abo_file
cov.file <- opts$cov_file
bc.file <- opts$bc_file
uu.file <- opts$uu_file
wu.file <- opts$wu_file
n <- as.numeric(opts$n)
nproc <- as.numeric(opts$nproc)
outpath <- opts$outpath

#abo.file <- "../results/pABO/abo.table.pABO.txt"
#cov.file <- "../results/pABO/covs.table.pABO.txt"
#bc.file <- "../results/pABO/beta.div.bc.pABO.txt"
#wu.file <- "../results/pABO/beta.div.wu.pABO.txt"
#uu.file <- "../results/pABO/beta.div.uu.pABO.txt"
#n <- 100
#nproc <- 4
#outpath <- "../results/pABO/8_beta_diversity/"



##### Load libraries:
library("testit")
#suppressMessages(library("foreach"))
#suppressMessages(library("doParallel"))
library("reshape2")
library(parallel)



##### Load data:
print("loading data")
abo <- read.table(file=abo.file, header=TRUE, stringsAsFactors=FALSE)
covs <- read.table(file=cov.file, header=TRUE, stringsAsFactors=FALSE)
bc <- read.table(file=bc.file, sep="\t", header=TRUE, stringsAsFactors=FALSE)
wu <- read.table(file=wu.file, sep="\t", header=TRUE, stringsAsFactors=FALSE)
uu <- read.table(file=uu.file, sep="\t", header=TRUE, stringsAsFactors=FALSE)



##### Generate output table if it isn't there already:
if (!file.exists(outpath)) {
	print(paste0("creating ",outpath," in filesystem"))
	dir.create(file.path(outpath))
}



##### Keep only one twin per family:
# Cut off that last number from TwinID so we have the pairs by number:
covs$i.TwinID <- substr(covs$i.TwinID, 1, nchar(covs$i.TwinID)-1)

# Remove one twin from each family:
rmme <- which(duplicated(covs[,"i.TwinID"]))
abo2 <- abo[-rmme,]
covs2 <- covs[-rmme,]

bc2 <- as.matrix(bc[-rmme, -rmme])
wu2 <- as.matrix(wu[-rmme, -rmme])
uu2 <- as.matrix(uu[-rmme, -rmme])



## EJC: corresponding to lines 110-217

##### Create melted distance table for each distance metric with either ABO or SS labels:

bc2[upper.tri(bc2, diag=T)] <- NA
wu2[upper.tri(wu2, diag=T)] <- NA
uu2[upper.tri(uu2, diag=T)] <- NA

melt.dist <- melt(bc2)
names(melt.dist) <- c("ID1", "ID2", "bc2")

# add other distance metrics
melt.dist$wu2 <- melt(wu2)$value
melt.dist$uu2 <- melt(uu2)$value

# remove NA rows
melt.dist <- melt.dist[!is.na(melt.dist$bc2), ]

# map ABO and secretor status
i1.idx <- match(melt.dist$ID1, colnames(bc2))
i2.idx <- match(melt.dist$ID2, colnames(bc2))
abo.i1 <- abo2$ABO[i1.idx]
abo.i2 <- abo2$ABO[i2.idx]
ss.i1 <- abo2$secretor_status[i1.idx]
ss.i2 <- abo2$secretor_status[i2.idx]

# make group calls
abo.group <- ifelse(abo.i1 == abo.i2, "within", "btwn")
ss.group <- ifelse(ss.i1 == ss.i2, "within", "btwn")


##### Calculate actual t-test p-value:

abo.p <- sapply(melt.dist[, 3:5], function(d) t.test(d ~ abo.group)$p.value)
ss.p <- sapply(melt.dist[, 3:5], function(d) t.test(d ~ ss.group)$p.value)

# NOTE: different order of p-values
actual.ps <- c(abo.p, ss.p)
names(actual.ps) <- c("bc_abo", "wu_abo", "uu_abo", "bc_ss", "wu_ss", "uu_ss")

##### Run the permutations:
print("running permutations in parallel")

# Start time:
strt <- Sys.time()

# generate sample permutations
ID.idx <- 1:ncol(bc2)
perm.list <- lapply(1:n, function(x) sample(ID.idx))

perm.out <- mclapply(perm.list, function(j)
{	
	# Apply permuted sample indices
	i1.idx <- match(melt.dist$ID1, colnames(bc2)[j])
	i2.idx <- match(melt.dist$ID2, colnames(bc2)[j])

	# map ABO and secretor status
	abo.i1 <- abo2$ABO[i1.idx]
	abo.i2 <- abo2$ABO[i2.idx]
	ss.i1 <- abo2$secretor_status[i1.idx]
	ss.i2 <- abo2$secretor_status[i2.idx]

	# make group calls
	abo.group <- ifelse(abo.i1 == abo.i2, "within", "btwn")
	ss.group <- ifelse(ss.i1 == ss.i2, "within", "btwn")

	# Calculate permutation p-values for each distance metric and ABO/SS:
	abo.p <- sapply(melt.dist[, 3:5], function(d) t.test(d ~ abo.group)$p.value)
	ss.p <- sapply(melt.dist[, 3:5], function(d) t.test(d ~ ss.group)$p.value)
	
	return(c(abo.p, ss.p))
	
}, mc.cores=nproc)

print(Sys.time() - strt)



##### Calculate permutation p-value:
print("calculating permutation p-values")

# NOTE: different order of p-values
permutations <- do.call(rbind, perm.out)
colnames(permutations) <- c("bc_abo", "wu_abo", "uu_abo", "bc_ss", "wu_ss", "uu_ss")

permutation.p <- sapply(1:length(actual.ps), function(ii) length(which(permutations[, ii] <= actual.ps[ii]))/n)

all.ps <- rbind(permutation.p, actual.ps, permutations)
rownames(all.ps)[1:2] <- c("permutation_p", "t.test_p")



##### Write out table:
print("writing out table of p-values")
write.table(all.ps, paste0(outpath, "beta_div_t_test_permutations_n_",n,"_",today,"ERD.txt"), sep="\t", quote=FALSE)



print("DONE!")


	